name: ws-scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ws-scan:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/android-ws-scan.yml@v0.28.9
    with:
      whitesource_product_name: my-product
    secrets: inherit