name: db-bundle

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/db-bundle.yml@v0.26.3
    with:
      migrations_project_path: path/to/migrations.csproj
      startup_project_path: path/to/startup.csproj
    secrets:
      GH_READ_PACKAGES_TOKEN: ${{ secrets.GH_READ_PACKAGES_TOKEN }}
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
