name: db-bundle

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/db-bundle.yml@v0.32.7
    with:
      migrations_project_path: path/to/migrations.csproj
      startup_project_path: path/to/startup.csproj
    secrets: inherit
