name: ci-nuget-publish

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-nuget-publish:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-ci.yml@main
    with:
      set_version: true
      run_pack: true
    secrets: inherit
