name: whitesource-scan

on:
  schedule:
    - cron: "*/5 * * * *"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-ws-scan.yml@v0.3.0
    with:
      use_apac_github_nuget: true
      whitesource_product_name: my-product
    secrets: 
      whitesource_api_key: ${{ secrets.WHITESOURCE_API_KEY }}
      whitesource_agent_url: ${{ secrets.WHITESOURCE_AGENT_URL }}     
      gh_read_packages_token: ${{ secrets.GH_READ_PACKAGES_TOKEN }}