name: ci

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-ci.yml@v0.9.2
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}