name: ws-scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-scan:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-ws-scan.yml@v0.7.20
    with:
      whitesource_product_name: my-product
    secrets: 
      whitesource_api_key: ${{ secrets.WHITESOURCE_API_KEY }}
      whitesource_agent_url: ${{ secrets.WHITESOURCE_AGENT_URL }}