name: ci

on:
  push:
    branches:
      [ $default-branch ]
  pull_request:
    branches:
      [ $default-branch ]
    types: [opened, synchronize, reopened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnetframework-ci.yml@v0.6.2
    with:
      projects: MyApp.NetFramework.sln
      runs_on_os: windows-latest
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
      