name: build

on:
  push:
    branches:
      - [ $default-branch ]
  pull_request:
    branches:
      - [ $default-branch ]
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-framework-build.yml@v0.1.45
    with:
      project: Test.NetFramework.sln
      run_tests: true      
      sonar_exclude: 'Test.NetFramework.UnitTest/**/*.*'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
      sonar_host_url: ${{ secrets.SONAR_HOST_URL }}