name: whitesource-scan

on:
  schedule:
    - cron: "0 1 * * 0"

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-analyze:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnetframework-ws-scan.yml@v0.6.32
    with:
      projects: MyApp.NetFramework.sln
      whitesource_product_name: my-product
      runs_on_os: windows-latest
    secrets: 
      whitesource_api_key: ${{ secrets.WHITESOURCE_API_KEY }}
      whitesource_agent_url: ${{ secrets.WHITESOURCE_AGENT_URL }}