name: ci

on:
  workflow_dispatch:
  push:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/dotnet-ci.yml@v0.8.3
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}