name: jirafy-prs

on:
  pull_request:
    types: [opened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-pr:
    uses: TAG-APAC-Division/platform-reusable-workflows/.github/workflows/jirafy-prs.yml@v0.30.6
    secrets: inherit
